### PR TITLE
Adding meta data

### PR DESCRIPTION
**Pull request by max-hassani**
Adding `meta.json` to the template to include the essential metadata

### CODE REVIEW

**Comment by jan-janssen** [comment]
I still disagree with adding a docker ID in the meta data. There is no one to one relationship between the workflows and the docker containers, but instead these are many to many relationships. One workflow can be executed in multiple docker containers as long as the required conda dependencies are installed and as a consequence inside one docker container multiple workflows can be installed.

**Comment by max-hassani** [comment]
> I still disagree with adding a docker ID in the meta data. There is no one to one relationship between the workflows and the docker containers, but instead these are many to many relationships. One workflow can be executed in multiple docker containers as long as the required conda dependencies are installed and as a consequence inside one docker container multiple workflows can be installed.

@jan-janssen, You are right. I have deleted it. The compatibility with various PMD docker images can be set in the registration process by the workflow store.

**Comment by max-hassani** [comment]
@jan-janssen, do you see any other changes necessary?

**Comment by jan-janssen** [comment]
The other question I ask myself is can we automatically get the information for certain fields like:
```
        "git_url": "the url of the remote git repository",
         "release": {
             "latest_release_date": "e.g., 2021-04-07",
             "latest_release_tag": "e.g., 0.0.1"
         },
         "state": {
             "development_status": "development/production",
             "regisration": "True/False",
             "CI/CD": "Passing/Failing"
         },
```
The `git_url` is the url of the repository, so it can be determined automatically, the same applies for `CI/CD` in particular as those might change when the user is not updating their repository. And something like `development_status` while in theory this is clearly defined in science these border vanish. So I would say every release should have `production` quality while the master branch can be `development`. Finally I do not really understand the field `regisration` what is this used for?

**Comment by max-hassani** [comment]
> 
> 
> The other question I ask myself is can we automatically get the information for certain fields like:
> 
> ```
>         "git_url": "the url of the remote git repository",
>          "release": {
>              "latest_release_date": "e.g., 2021-04-07",
>              "latest_release_tag": "e.g., 0.0.1"
>          },
>          "state": {
>              "development_status": "development/production",
>              "regisration": "True/False",
>              "CI/CD": "Passing/Failing"
>          },
> ```
> 
> The `git_url` is the url of the repository, so it can be determined automatically, the same applies for `CI/CD` in particular as those might change when the user is not updating their repository. And something like `development_status` while in theory this is clearly defined in science these border vanish. So I would say every release should have `production` quality while the master branch can be `development`. Finally I do not really understand the field `regisration` what is this used for?

I understand that some fields can be derived automatically, but I thought since these keys are supposed to be stored in a sql database and make it able to be queried, it is better to be read from the meta.json file directly. Although I agree that their addition can increase the chance of human error. So I will remove them.
About the production/development status, I just tried to implement your suggestion from [here](https://github.com/orgs/materialdigital/teams/administratives/discussions/1/comments/1). 
Now, I also see that registration is also redundant.

**Comment by max-hassani** [comment]
To document everything here in the pull request, I will copy below Tilmann comments as well:
- since we want to use the information for the PMD app store, we should mention the workflow environment (i.e. pyiron vs. simstack) as well
- though there is no connection to a specific docker image, I think we should still provide a category such as atomistic, continuum, experimental
- having the comment of Jörg U. in mind, we should perhaps also include the major steps/codes involved; this may also be a copy of the information given in the yaml file, but the information should be searchable in the repository, e.g. "provide me all workflows that involve elastic constants" or "provide me all workflows that involve a Lammps calculation

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Pull request merged**
